CabinetOpt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import custom_404_handler, custom_500_handler, custom_403_handler


handler404 = custom_404_handler
handler500 = custom_500_handler
handler403 = custom_403_handler

urlpatterns = [
    path('admin/'       , admin.site.urls),
    path('api-auth/'    , include('rest_framework.urls')),
    path('clients/'     , include('clients.urls')),
    path('users/'       , include('users.urls')),
    path('catalog/'     , include('catalog.urls')),
    path('orders/'      , include('orders.urls')),
    path('cart/'        , include('cart.urls')),
    path('summernote/'  , include('django_summernote.urls')),
    path('condition/'   , include('settings_and_conditions.urls')),
    path('django-rq/'   , include('django_rq.urls')),
    path('shared_links/', include('shared_links.urls')),
    path('', render, kwargs={'template_name': 'index.html'}, name='start_page'),
    path('forbidden/'   , views.forbidden_view, name='forbidden_view'),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/' , include('debug_toolbar.urls')),
        path('silk/', include('silk.urls', namespace='silk')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, register_converter
from django.urls.converters import SlugConverter


from . import views
    
class SizeConverter:
    regex = '[.-a-zA-Z0-9_]*'

    def to_python(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value

    def to_url(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value    

register_converter(SizeConverter, 'size')

app_name = "cart"
urlpatterns = [
    path(''                                     , views.cart_detail, name='cart_detail'),
    path('send/<str:product_id>/'               , views.send_to_cart),
    path('add/<str:product_id>/'                , views.cart_add, name='cart_add'),
    path('add/sizes/<str:product_id>/'          , views.cart_add_sizes, name='cart_add_sizes'),
    path('info/'                                , views.cart_info),
    path('info/<str:product_id>/'               , views.cart_info),
    path('info/<str:product_id>/<size:size>'    , views.cart_info),
    path('remove/<str:product_id>/'             , views.cart_remove, name='cart_remove'),
    path('remove/<str:product_id>/<size:size>'  , views.cart_remove_size, name='cart_remove_size'),
    path('order/create/'                        , views.add_order, name='create'),
    path('errors/'                              , views.cart_detail_with_errors, name='errors'),
    path('product/<str:prod_id>/'               , views.edit_product, name='product_editing'),
]

catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path('filters/'                       , views.FiltersView.as_view()),
    path('products/'                      , views.ProductView.as_view(), name='products'),
    path('products/<str:key>/'            , views.ProductView.as_view()),
    # path('сertificates/'                  , views.CertificateView.as_view(), name='сertificates'),
    # path('services/'                      , views.ServiceView.as_view(), name='services'),
    path('product/<slug:prod_id>/'        , views.ProductCardView.as_view(), name='product'),
    path('upload/products'                , views.upload_products),
    path('remove/images/<slug:prod_id>'   , views.remove_images),
    path('upload/images'                  , views.upload_images),
    path('upload/videos'                  , views.upload_videos),
    path('upload/price'                   , views.upload_price),
    path('upload/stock_and_costs'         , views.upload_stock_and_costs),
    path('pickup_products/'               , views.pickup_products),
    path('stocks_and_costs/'              , views.stocks_and_costs),
    path('product/accessories'            , views.product_accessories),
    path('product/analogues'              , views.product_analogues),
    path('product/alike-products'         , views.alike_products),
    path('product/sizes/<slug:prod_id>/'  , views.sizes_selection, name='sizes_selection'),
    path('products/pages/count/'          , views.catalog_pages_count),
    path('search-error/'                  , views.search_error),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path('reg_request/'            , views.register, name='reg_request'),
    path('reg_request_confirm/'    , views.register_confirm, name='reg_request_confirm'),
    path('login/'                  , views.login, name='login'),
    path('logout/'                 , views.logout, name='logout'),
    path('check_login/'            , views.check_login, name='check_login'),
    path('login_recovery/'         , views.login_recovery, name='login_recovery'),
    path('change_pass/<str:id>/'   , views.change_password, name='change_pass'),
    path('request_pass/'           , views.request_password, name='request_pass'),
    path('recovery_pass/<str:id>/' , views.recovery_password, name='recovery_pass'),
    path('contact/'                , views.ContactDetailView.as_view(), name='contact'),
    path('contact/edit/<str:id>/'  , views.ContactDetailEditView.as_view(), name='edit'),
    path('contact/edit/'           , views.ContactDetailCreateView.as_view(), name='edit'),
    path('manager/'                , views.ManagerView.as_view(), name='manager'),
    path('manager/add/'            , views.ManagerAddView.as_view(), name='add_manager'),
    path('generate-password/'      , views.generate_password, name='generate_password'),
]

orders/urls.py
from django.urls import path, register_converter
from datetime import datetime

from . import views

class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value    

register_converter(DateConverter, 'data')

app_name = "orders"
urlpatterns = [
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('order/edit/<slug:order_id>/', views.EditOrderView.as_view(), name='edit'),
    path('order/update/<slug:order_id>/', views.UpdateOrderView.as_view(), name='update'),
    path('order/split/<slug:order_id>/', views.SplitOrderView.as_view(), name='split'),
    path('order/remove/<slug:order_id>/', views.remove_order, name='remove'),
    path('order/create/<slug:order_id>/', views.CreateOrderView.as_view(), name='create'),
    path('order/item/create', views.add_order_item),
    path('stocks_and_costs/', views.stocks_and_costs),
    path('order/export', views.unload_orders),
    path('order/export/<data:data_from>', views.unload_orders),
    path('order/export/<data:data_from>/<data:data_to>', views.unload_orders),
    path('order/export/pdf/<slug:order_id>/', views.ExportPDFView.as_view(), name='export-pdf'),
    path('order/export/xlsx/<slug:order_id>/', views.ExportXLSXView.as_view(), name='export-xlsx'),
    path('order/import/xlsx/', views.import_xlsx, name='import-xlsx'),
    path('order/update/number', views.update_order_number),
    path('order/product/<str:order_id>/<str:prod_id>/', views.edit_product, name='product_editing'),
]

catalog/models.py
from django.db import models
from contextlib import suppress
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db.models import F, Q, Max
from django.utils import timezone

from clients.models import Client


class TrimCharField(models.CharField):
    def __init__(self, *args, **kwargs):
        # Добавляем свои дополнительные параметры, в данном случае
        # strip для автоматического удаления пробелов
        self.strip = kwargs.pop('strip', False)

        # Вызываем конструктор родительского класса
        super().__init__(*args, **kwargs)

    def pre_save(self, model_instance, add):
        # Логика обработки поля перед сохранением
        if self.strip and hasattr(model_instance, self.attname):
            value = getattr(model_instance, self.attname)

            if isinstance(value, str):
                # Удаляем пробелы, если параметр strip установлен в True
                setattr(model_instance, self.attname, value.strip())

        # Вызываем метод pre_save родительского класса
        return super().pre_save(model_instance, add)



class СategoryGroup(models.Model):
    name = models.CharField('Наименование', max_length=100, db_index=True)
    order = models.PositiveIntegerField(
        'Порядок', default=1, validators=[MinValueValidator(0)]
    )
    class Meta:
        verbose_name = 'Группа товара'
        verbose_name_plural = 'Группы товаров'

    def __str__(self):
        return self.name


class Сategory(models.Model):
    group = models.ForeignKey(
        СategoryGroup,
        on_delete=models.PROTECT,
        verbose_name='Группа',
        related_name='сategories',
        db_index=True,
    )
    name = models.CharField('Наименование', max_length=100, db_index=True)
    discount = models.DecimalField(
        'Скидка',
        max_digits=8,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0)]
    )
    identifier_1C = models.CharField(
        'Идентификатор 1С', max_length=50, blank=True, db_index=True
    )

    class Meta:
        verbose_name = 'Подгруппа товара'
        verbose_name_plural = 'Подгруппы товаров'

    def __str__(self):
        return self.name


class Collection(models.Model):
    name = models.CharField('Наименование', max_length=100, db_index=True)

    class Meta:
        verbose_name = 'Коллекция'
        verbose_name_plural = 'Коллекции'

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField('Наименование', max_length=50)
    identifier_1C = models.CharField(
        'Идентификатор 1С', max_length=50, blank=True, db_index=True
    )
    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField('Гендер', max_length=100, db_index=True)

    class Meta:
        verbose_name = 'Гендер'
        verbose_name_plural = 'Гендер'

    def __str__(self):
        return self.name


class MetalFinish(models.Model):
    name = models.CharField('Обработка металла', max_length=100, db_index=True)

    class Meta:
        verbose_name = 'Вид обработки металла'
        verbose_name_plural = 'Виды обработки металла'

    def __str__(self):
        return self.name


class Gift(models.Model):
    name = models.CharField('Подарок', max_length=100, db_index=True)

    class Meta:
        verbose_name = 'Подарок'
        verbose_name_plural = 'Подарки'

    def __str__(self):
        return self.name


class Style(models.Model):
    name = models.CharField('Стиль', max_length=100, db_index=True)

    class Meta:
        verbose_name = 'Стиль'
        verbose_name_plural = 'Стили'

    def __str__(self):
        return self.name


class Design(models.Model):
    name = models.CharField('Дизайн', max_length=100, db_index=True)

    class Meta:
        verbose_name = 'Дизайн изделия'
        verbose_name_plural = 'Дизайны изделий'

    def __str__(self):
        return self.name


class ProductQuerySet(models.QuerySet):
    
    def apply_filters(self, filters):
        result = self.distinct()
        for key, value in filters.items():
            if key == 'name':
                result = result.filter(name__in=value.split(';'))
            elif key == 'articul':
                result = result.filter(articul__icontains=value)
            elif key == 'unit':
                result = result.filter(unit=value)
            elif key == 'status':
                result = result.filter(status=value)
        return result
    
    def get_active_products(self, in_stock=True):
        result = self.distinct()
        result = result.filter(product_type='product', show_on_site=True)
        result = result.filter(
            id__in=Price.objects.filter(type__name="Базовая", price__gt=0).values_list("product", flat=True)
        )
        result = result.filter(
            id__in=ProductImage.objects.all().values_list("product", flat=True)
        )
        if in_stock:
            result = result.filter(
                pk__in=StockAndCost.objects.filter(
                    stock__gte=1
                ).values_list('product_id', flat=True)
            )
        return result


class Product(models.Model):
    NOVELTY   = 'new'
    HIT       = 'hit'
    SALE      = 'sale'
    PROFIT    = 'profit'
    EXCLUSIVE = 'exclusive'

    STATUS_CHOICES = (
        (NOVELTY   , 'NEW!'),
        (HIT       , 'ХИТ'),
        (SALE      , 'SALE'),
        (PROFIT    , 'ВЫГОДНО'),
        (EXCLUSIVE , 'ЭКСКЛЮЗИВ'),
    )

    name = models.CharField('Наименование', max_length=200, db_index=True)
    articul = models.CharField('Артикул', max_length=200, blank=True)
    сategory = models.ForeignKey(
        Сategory,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='сategory_products',
        db_index=True,
    )
    brand = models.ForeignKey(
        Brand,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Бренд',
        related_name='brand_products'        
    )
    сollection = models.ForeignKey(
        Collection,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Коллекция',
        related_name='сollection_products',
        db_index=True,
    )
    unit = models.CharField(
        'Единица измерения',
        max_length=20,
        default='грамм',
        db_index=True,
        choices=(
            ('796', 'штук'),
            ('163', 'грамм'),
    ))
    available_for_order = models.BooleanField(
        'Доступен для заказа', default=False, db_index=True
    )
    show_on_site = models.BooleanField(
        'Показывать на сайте', default=True, db_index=True
    )
    created_at = models.DateTimeField(
        'Дата создания', db_index=True, auto_now_add=True
    )
    product_type = models.CharField(
        'Тип',
        max_length=20,
        default='product',
        db_index=True,
        choices=(
            ('product', 'товар'),
            ('service', 'услуга'),
            ('gift_сertificate', 'подарочный сертификат')
    ))
    metal = TrimCharField('Металл', max_length=50, blank=True, db_index=True, strip=True)
    metal_content = TrimCharField('Проба', max_length=30, blank=True, db_index=True, strip=True)
    metal_finish = models.ManyToManyField(
        MetalFinish,
        verbose_name='Обработка металла',
        related_name='products_by_gender'
    )
    color = TrimCharField('Цвет', max_length=50, blank=True, db_index=True, strip=True)
    gender = models.ManyToManyField(
        Gender,
        verbose_name='Гендер',
        related_name='products_by_gender'
    )
    status = models.CharField(
        'Статус',
        max_length=20,
        blank=True,
        db_index=True,
        choices=STATUS_CHOICES)
    gift = models.ManyToManyField(
        Gift,
        verbose_name='Подарок',
        related_name='products_by_gift'
    )
    style = models.ManyToManyField(
        Style,
        verbose_name='Стиль',
        related_name='products_by_style'
    )
    design = models.ManyToManyField(
        Design,
        verbose_name='Дизайн',
        related_name='products_by_design'
    )
    str_color = TrimCharField('Цвет строкой', max_length=50, blank=True, db_index=True, strip=True)
    lock_type_earings = models.CharField('Тип и размер замка серег', max_length=50, blank=True, db_index=True)
    lock_type_chain = models.CharField('Тип и размер замка цепей', max_length=50, blank=True, db_index=True)
    lock_type_bracelet = models.CharField('Тип и размер замка браслетов', max_length=50, blank=True, db_index=True)
    chain_width = models.IntegerField(
        'Ширина цепи',
        default=0,
        validators=[MinValueValidator(0)]
    )
    bracelet_width = models.IntegerField(
        'Ширина браслета',
        default=0,
        validators=[MinValueValidator(0)]
    )
    q_borders_c_b = models.IntegerField(
        'Количество граней',
        default=0,
        validators=[MinValueValidator(0)]
    )
    chain_weave = models.CharField('Плетение (для цепей)', max_length=50, blank=True, db_index=True)
    bracelet_weave = models.CharField('Плетение (для браслетов)', max_length=50, blank=True, db_index=True)
    mark_description = models.TextField('Маркетинговое описание', blank=True)
    identifier_1C = models.CharField(
        'Идентификатор 1С', max_length=50, blank=True, db_index=True
    )

    objects = ProductQuerySet.as_manager()

    class Meta:
        verbose_name = 'Номенклатура'
        verbose_name_plural = 'Номенклатура'

    def __str__(self):
        return f'{self.articul} {self.name}'.strip()
    
    def natural_key(self):
        return (self.name, self.id, self.identifier_1C, )
    
    @property
    def get_images(self):

templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Личный кабинет ЮЛ</title>

        <link rel="icon" href="{% static 'icon.png' %}" type="image/x-icon">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'index.css' %}">
    </head>
    <body>

        <nav class="navbar navbar-light fixed-top bg-light flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
                <h1>Talant</h1>
            </a>    
            {% if not request.session.login %}
                <div>
                    <button
                        id="loginButton"
                        class="btn btn-outline-primary login-btn"
                        data-toggle="modal"
                        data-target="#loginForm"
                        data-url="{% url 'clients:login' %}" 
                    >                    
                        <!-- атрибут data-url исп. для передачи относительного адреса в файл index.js
                        так как он не имеет доступа к контексту Django  -->
                        <span><i class="fa fa-money"></i></span>
                        <span class="btn-text text-default">Войти</span>
                    </button>
                    <button
                        id="regRequestButton"
                        class="btn btn-outline-secondary login-btn"
                        data-toggle="modal"
                        data-target="#regRequestForm"
                        data-url="{% url 'clients:reg_request' %}" 
                    >
                        <span><i class="fa fa-money"></i></span>
                        <span class="btn-text text-default">Зарегистрироваться</span>
                    </button>
                </div>
            {% else %}
                <div class="login_block">
                    <div class="login_text">{{ request.session.login }}</div>
                    <a href="{% url 'clients:logout' %}">
                        <button
                            id="logoutButton"
                            class="btn btn-outline-secondary login-btn"
                        >
                            <span><i class="fa fa-money"></i></span>
                            <span class="btn-text text-default">Выйти</span>
                        </button>
                    </a>
                </div>
            {% endif %}
        </nav>

        <div class="container-fluid">
            {% if request.session.login %}
                <div class="row"> 
                    {% include 'sidebar.html' %}             
                </div>

                <main role="main" class="ml-sm-auto col-lg-10 px-4">
                    {% block page %}
                        {% block content %}
                        {% endblock %}
                    {% endblock %}
                </main>
            {% endif %}
        </div>

        <div class="modal fade" id="loginForm" tabindex="-1" role="dialog">
            {% include 'login.html' %}
        </div>

        <div class="modal fade" id="regRequestForm" tabindex="-1" role="dialog">
            {% include 'reg_order.html' %}
        </div>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'index.js' %}"></script>
    </body>
</html>

templates/pages/contact.html
{% extends "main.html" %}
{% load humanize %}

{% block page %}
	{% block content %}

    <div class="container-fluid order-list-wrapper">
        <div class="order-list-wrapper__breadcrumb-wrapper">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'catalog:products' %}">Ювелирный интернет-магазин TALANT</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Аккаунт</li>
                </ol>
            </nav>
        </div>

        <div class="row">
            <div id="contact-container" class="container col-3 contact-detail">

                <div class="font-weight-bold contact-detail__client">{{ client.name }}</div>
                <div class="font-weight-bold contact-detail__client">{{ manager }}</div>
                <div class="contact-detail__client__position"></div>
                <div>
                    <p class="font-weight-normal contact-detail__item-title">ИНН</p>
                    <span class="font-weight-bold contact-detail__item">{{ client.inn }}</span>
                    <div class="contact-detail__item__position"></div>
                </div>
                <div>
                    <p class="font-weight-normal contact-detail__item-title">Логин</p>
                    <span class="font-weight-bold contact-detail__item">Login {{ login.login }}</span>
                    <div class="contact-detail__item__position"></div>
                </div>

                {% if hash_inn %}
                <a href="{% url 'clients:change_pass' hash_id %}?usr={{ hash_inn }}" class="contact-detail__change_pass" target="_blank">Сменить пароль</a>
                {% endif %}
                <div class="contact-detail__change_pass__position"></div>

                <div class="font-weight-normal contact-detail__item">E-mail: {{ manager.email }}</div>
                <div class="font-weight-normal contact-detail__item">телефон: {{ manager.phone }}</div>
                <div class="contact-detail__item__position"></div>
                <a 
                    class="contact-detail__change_pass"
                    name="add-new-manager"
                    href="javascript:void(0);">
                    <u>Добавить нового менеджера</u>
                </a>
                <div class="contact-detail__item__position-x2"></div>

                <div>
                    <p>Ваш персональный менеджер:</p>

                    <p class="font-weight-bold contact-detail__manager_talant">{{ client.manager_talant }}</p>
                    <p class="font-weight-bold contact-detail__manager_talant">{{ client.manager_talant.email }}</p>
                    <p class="font-weight-bold contact-detail__manager_talant">{{ client.manager_talant.phone }}</p>
                </div>

            </div>

            <div class="container col-9">
                <div id="orders-container">

                    <div class="orders-detail">
                        <div class="orders__title">Заказы</div>
                        <div class="orders-detail__wrapper">
                            <div class="orders-items">
                                <table id="orders-items" class="table table__thead--border order-preview__table orders-list">
                                    <thead>
                                        <tr>
                                            <th scope="col" class="title">
                                                <span>
                                                    <i class="fa fa-sort-amount-desc"></i>
                                                    <i class="fa fa-sort-amount-asc"></i>
                                                    Заказ №
                                                    <i class="fa fa-angle-down"></i>
                                                    <i class="fa fa-angle-up"></i>
                                                </span>
                                            </th>
                                            <th scope="col" class="title">
                                                <span>
                                                    <i class="fa fa-sort-amount-desc"></i>
                                                    <i class="fa fa-sort-amount-asc"></i>
                                                    Дата
                                                    <i class="fa fa-angle-down"></i>
                                                    <i class="fa fa-angle-up"></i>
                                                </span>
                                            </th>
                                            <th scope="col" class="title">
                                                <span>
                                                    <i class="fa fa-sort-amount-desc"></i>
                                                    <i class="fa fa-sort-amount-asc"></i>
                                                    Сумма, руб
                                                    <i class="fa fa-angle-down"></i>
                                                    <i class="fa fa-angle-up"></i>
                                                </span>
                                            </th>
                                            <th scope="col" class="title">
                                                <span>
                                                    <i class="fa fa-sort-amount-desc"></i>
                                                    <i class="fa fa-sort-amount-asc"></i>
                                                    вес, г
                                                    <i class="fa fa-angle-down"></i>
                                                    <i class="fa fa-angle-up"></i>
                                                </span>
                                            </th>
                                            <th scope="col" class="title">
                                                <span>
                                                    <i class="fa fa-sort-amount-desc"></i>
                                                    <i class="fa fa-sort-amount-asc"></i>
                                                    Кол-во, шт
                                                    <i class="fa fa-angle-down"></i>
                                                    <i class="fa fa-angle-up"></i>
                                                </span>
                                            </th>
                                            <th scope="col" class="title">
                                                <span>
                                                    <i class="fa fa-sort-amount-desc"></i>
                                                    <i class="fa fa-sort-amount-asc"></i>
                                                    Статус
                                                    <i class="fa fa-angle-down"></i>
                                                    <i class="fa fa-angle-up"></i>
                                                </span>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for order in orders %}
                                        <tr>
                                            <td class="font-weight-bold">{{ order.id }}_{{ order.provision }}</td>
                                            <td class="font-weight-bold">{{ order.created_at|date:'d-m-Y' }}</td>
                                            <td class="font-weight-bold">{{ order.get_total_cost|floatformat:0|intcomma }}</td>
                                            <td class="font-weight-bold">{{ order.get_total_weight|floatformat:3 }}</td>
                                            <td class="font-weight-bold">{{ order.get_total_quantity|floatformat:0 }}</td>
                                            <td class="font-weight-bold">{{ order.get_status_display }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
    
        </div>

    </div>

    <div class="add-manager-form-layout hidden" id="add-manager-form"></div>

	{% endblock %}
{% endblock %}

templates/pages/orders.html
{% extends "main.html" %}
{% load order_tags %}

{% block page %}
	{% block content %}
        <div class="container-fluid order-list-wrapper">
            <div class="order-list-wrapper__breadcrumb-wrapper">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'catalog:products' %}">Ювелирный интернет-магазин TALANT</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Заказы</li>
                    </ol>
                </nav>
            </div>
            <div class="d-flex flex-row">
                <div class="order-list col-3">
                    {% include "components/orders/list.html" with orders=orders %}
                </div>
                <div id="order" class="order-detail__wrapper"></div>
            </div>
        </div>
	{% endblock %}
{% endblock %}