CabinetOpt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import custom_404_handler, custom_500_handler, custom_403_handler


handler404 = custom_404_handler
handler500 = custom_500_handler
handler403 = custom_403_handler

urlpatterns = [
    path('admin/'       , admin.site.urls),
    path('api-auth/'    , include('rest_framework.urls')),
    path('clients/'     , include('clients.urls')),
    path('users/'       , include('users.urls')),
    path('catalog/'     , include('catalog.urls')),
    path('orders/'      , include('orders.urls')),
    path('cart/'        , include('cart.urls')),
    path('summernote/'  , include('django_summernote.urls')),
    path('condition/'   , include('settings_and_conditions.urls')),
    path('django-rq/'   , include('django_rq.urls')),
    path('shared_links/', include('shared_links.urls')),
    path('', render, kwargs={'template_name': 'index.html'}, name='start_page'),
    path('forbidden/'   , views.forbidden_view, name='forbidden_view'),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/' , include('debug_toolbar.urls')),
        path('silk/', include('silk.urls', namespace='silk')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, register_converter
from django.urls.converters import SlugConverter


from . import views
    
class SizeConverter:
    regex = '[.-a-zA-Z0-9_]*'

    def to_python(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value

    def to_url(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value    

register_converter(SizeConverter, 'size')

app_name = "cart"
urlpatterns = [
    path(''                                     , views.cart_detail, name='cart_detail'),
    path('send/<str:product_id>/'               , views.send_to_cart),
    path('add/<str:product_id>/'                , views.cart_add, name='cart_add'),
    path('add/sizes/<str:product_id>/'          , views.cart_add_sizes, name='cart_add_sizes'),
    path('info/'                                , views.cart_info),
    path('info/<str:product_id>/'               , views.cart_info),
    path('info/<str:product_id>/<size:size>'    , views.cart_info),
    path('remove/<str:product_id>/'             , views.cart_remove, name='cart_remove'),
    path('remove/<str:product_id>/<size:size>'  , views.cart_remove_size, name='cart_remove_size'),
    path('order/create/'                        , views.add_order, name='create'),
    path('errors/'                              , views.cart_detail_with_errors, name='errors'),
    path('product/<str:prod_id>/'               , views.edit_product, name='product_editing'),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path('reg_request/'            , views.register, name='reg_request'),
    path('reg_request_confirm/'    , views.register_confirm, name='reg_request_confirm'),
    path('login/'                  , views.login, name='login'),
    path('logout/'                 , views.logout, name='logout'),
    path('check_login/'            , views.check_login, name='check_login'),
    path('login_recovery/'         , views.login_recovery, name='login_recovery'),
    path('change_pass/<str:id>/'   , views.change_password, name='change_pass'),
    path('request_pass/'           , views.request_password, name='request_pass'),
    path('recovery_pass/<str:id>/' , views.recovery_password, name='recovery_pass'),
    path('contact/'                , views.ContactDetailView.as_view(), name='contact'),
    path('contact/edit/<str:id>/'  , views.ContactDetailEditView.as_view(), name='edit'),
    path('contact/edit/'           , views.ContactDetailCreateView.as_view(), name='edit'),
    path('manager/'                , views.ManagerView.as_view(), name='manager'),
    path('manager/add/'            , views.ManagerAddView.as_view(), name='add_manager'),
    path('generate-password/'      , views.generate_password, name='generate_password'),
]

orders/urls.py
from django.urls import path, register_converter
from datetime import datetime

from . import views

class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value    

register_converter(DateConverter, 'data')

app_name = "orders"
urlpatterns = [
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('order/edit/<slug:order_id>/', views.EditOrderView.as_view(), name='edit'),
    path('order/update/<slug:order_id>/', views.UpdateOrderView.as_view(), name='update'),
    path('order/split/<slug:order_id>/', views.SplitOrderView.as_view(), name='split'),
    path('order/remove/<slug:order_id>/', views.remove_order, name='remove'),
    path('order/create/<slug:order_id>/', views.CreateOrderView.as_view(), name='create'),
    path('order/item/create', views.add_order_item),
    path('stocks_and_costs/', views.stocks_and_costs),
    path('order/export', views.unload_orders),
    path('order/export/<data:data_from>', views.unload_orders),
    path('order/export/<data:data_from>/<data:data_to>', views.unload_orders),
    path('order/export/pdf/<slug:order_id>/', views.ExportPDFView.as_view(), name='export-pdf'),
    path('order/export/xlsx/<slug:order_id>/', views.ExportXLSXView.as_view(), name='export-xlsx'),
    path('order/import/xlsx/', views.import_xlsx, name='import-xlsx'),
    path('order/update/number', views.update_order_number),
    path('order/product/<str:order_id>/<str:prod_id>/', views.edit_product, name='product_editing'),
]

orders/views.py
import simplejson as json

from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.contrib.staticfiles import finders
from django.contrib.auth import get_user_model
from django.core.serializers import serialize
from django.core.exceptions import ValidationError
from django.db.models import F, Sum, Count
from django.views.generic import (
    ListView, UpdateView, CreateView, TemplateView
)
from django.template.loader import get_template
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from collections import defaultdict
from contextlib import suppress

from more_itertools import first
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.serializers import ModelSerializer

# from xhtml2pdf import pisa

from clients.login import Login
from clients.models import Client, Manager, ContactDetail
from catalog.models import Product, StockAndCost, Size, PriceType
from orders.models import Order, OrderItem

from .forms import (
    OrderForm,
    OrderItemForm,
    OrderItemInline,
    FileSelectionForm
)
from .utils import save_xlsx, read_xlsx
from utils.exceptions import handle_errors
from settings_and_conditions.models import NotificationType
from settings_and_conditions.utils import notification_scheduling

from utils.requests import handle_get_params


class ProductSerializer(ModelSerializer):

    class Meta:
        model = Product
        fields = [
            'id',
            'name',
            'articul',
            'unit',
            'available_for_order',
            'show_on_site',
            'product_type',
            'metal',
            'metal_content',
            'color',
            'status',
            'identifier_1C'
        ]


class SizeSerializer(ModelSerializer):

    class Meta:
        model = Size
        fields = '__all__'


class OrderItemSerializer(ModelSerializer):

    product = ProductSerializer()
    size = SizeSerializer()

    class Meta:
        model = OrderItem
        fields = '__all__'


class UserSerializer(ModelSerializer):

    class Meta:
        model = get_user_model()
        fields = [
            'id',
            'is_superuser',
            'username',
            'is_active',
            'is_staff',
            'name',
            'email',
            'phone',
            'gender'
        ]


class ManagerSerializer(ModelSerializer):

    class Meta:
        model = Manager
        fields = ['id', 'name', 'email', 'phone', 'login']


class ClientSerializer(ModelSerializer):

    manager_talant = UserSerializer()
    manager = ManagerSerializer(many=True)

    class Meta:
        model = Client
        fields = '__all__'



class OrderSerializer(ModelSerializer):

    client = ClientSerializer()
    manager = ManagerSerializer()

    class Meta:
        model = Order
        fields = '__all__'


class OrderView(ListView):
    model = Order
    template_name = 'pages/orders.html'
    context_object_name = 'orders'
    allow_empty = True

    @handle_get_params()
    def get(self, request, *args, **kwargs):
        self.share_link = kwargs.get('link', '')
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        login = Login(self.request)
        current_clients = login.get_clients()
        if not current_clients:
            return super().get_queryset().order_by('-created_at')[:10]
        return Order.objects.filter(client__in=current_clients).order_by('-created_at')[:10]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context | {
            'order_items': OrderItem.objects.filter(order__in=context['orders']),
            'share_link' : self.share_link,
            'MEDIA_URL'  : settings.MEDIA_URL
        }


class EditOrderView(UpdateView):
    model = Order
    slug_url_kwarg, slug_field = 'order_id', 'pk'
    template_name = 'pages/order.html'
    success_url = reverse_lazy('orders')
    fields = ['status', 'client', 'manager',]

    def get_form(self):
        form = super().get_form()
        for field in form.fields:
            form.fields[field].widget.attrs['class'] = 'form-control'
        return form

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['order_items'] = OrderItemInline(self.request.POST, instance=self.object)
        else:
            context['order_items'] = OrderItemInline(instance=self.object)
        context['empty_items'] = context['order_items'].empty_form
        context['fields'] = [
            {"id": "_id_status", "label": "Статус:", "value": context['order'].get_status_display()},
            {"id": "_id_client", "label": "Клиент:", "value": context['order'].client},
            {"id": "_id_manager", "label": "Менеджер:", "value": context['order'].manager}
        ]

        # Возможно перенести в класс Login для свободного обмена токенами через SessionStorage
        # from users.models import CustomUser
        # context['auth'] = ''
        # token = Token.objects.filter(
        #     user__in=CustomUser.objects.filter(is_superuser=True)
        # ).first()
        # if (token):
        #     context['auth'] = token.key

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']
        if form.is_valid() and order_items.is_valid():
            current_status = form.instance.status
            with suppress(Order.DoesNotExist):
                current_order = Order.objects.get(pk=form.instance.id)
                current_status = current_order.status
            with transaction.atomic():
                form.instance.save()
                for order_item in order_items.deleted_forms:
                    order_item.instance.delete()
                order_items.save()
                schedule_send_order(form.instance, current_status)
        else:
            if form.errors:
                context['order_errors'] = form.errors
            if order_items.errors:
                context['order_items_errors'] = order_items.errors  
            
        return render(self.request, self.template_name, context)


class UpdateOrderView(UpdateView):
    model = Order
    slug_url_kwarg, slug_field = 'order_id', 'pk'
    template_name = 'pages/order.html'
    success_url = reverse_lazy('orders')
    fields = ['status', 'client', 'manager',]

    def get_form(self):
        form = super().get_form()
        for field in form.fields:
            form.fields[field].widget.attrs['class'] = 'form-control'
        return form

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['order_items'] = OrderItemInline(self.request.POST, instance=self.object)
        else:
            context['order_items'] = OrderItemInline(instance=self.object)
        context['empty_items'] = context['order_items'].empty_form
        context['fields'] = [
            {"id": "_id_status", "label": "Статус:", "value": context['order'].get_status_display()},
            {"id": "_id_client", "label": "Клиент:", "value": context['order'].client},
            {"id": "_id_manager", "label": "Менеджер:", "value": context['order'].manager}
        ]
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']
        if form.is_valid() and order_items.is_valid():
            current_status = form.instance.status
            with suppress(Order.DoesNotExist):
                current_order = Order.objects.get(pk=form.instance.id)
                current_status = current_order.status
            with transaction.atomic():
                form.instance.save()
                for order_item in order_items.deleted_forms:
                    order_item.instance.delete()
                order_items.save()
            
            schedule_send_order(form.instance, current_status)
        return redirect('orders:orders')


class SplitOrderView(TemplateView):
    slug_url_kwarg, slug_field = 'order_id', 'pk'
    template_name = 'pages/order.html'
    success_url = reverse_lazy('orders')
    fields = ['status', 'client', 'manager',]

    def split_products(self, order_items):
        _out_of_stock = []
        _in_stock = defaultdict(list)

        for item in order_items:
            product_id = item['product'].id
            if item.get('size') and item['size'].name:
                stocks = StockAndCost.objects.get_stocks(product_id, item['size'].name)
            else:
                stocks = StockAndCost.objects.get_stocks(product_id)   
            if not stocks:
                _out_of_stock.append(item)
                continue
            elif not stocks.get('total_stock', 0):
                _out_of_stock.append(item)
                continue
            elif stocks['total_stock'] < item['quantity']:
                current_stock = stocks['total_stock']
                item_out_of_stock = item.copy()
                item_out_of_stock['quantity'] = item['quantity'] - current_stock
                item_out_of_stock['total_price'] = item_out_of_stock['quantity'] * item_out_of_stock['price']
                _out_of_stock.append(item_out_of_stock)

                item['quantity'] = current_stock
                item['total_price'] = item['quantity'] * item['price']

            if item['quantity'] > 0:
                _in_stock[item['product'].metal].append(item)

        return _in_stock, _out_of_stock

    def get_context_data(self, *, object_list=None, **kwargs):

templates/forms/auth-recovery.html
{% load static %}

<form class="justify-content-xl-center login-recovery-form custom-card" method="post" action="{% url 'clients:request_pass' %}">
    <div class="d-flex flex-column flex-nowrap container">
        {% csrf_token %}
        <div class="d-sm-flex flex-row sign-in-form-item auth-form-title">
            <p id="title-part-1">ВХОД</p>
            <p class="cursor-pointer" id="title-part-2">
                /&nbsp;
                <a id="register" data-url="{% url 'clients:reg_request' %}">регистрация</a>
            </p>
        </div>
        <div>
            <p class="auth-form-errors"></p>
        </div>
        <div>
            {% for field in form %}
                <div class="sign-in-form-item">
                    <label class="default-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
        </div>
        <div class="text-center recovery-form-btn">
            <button class="btn btn-primary btn-sign-in font-weight-bold" type="submit">Восстановить пароль</button>
        </div>
        <a
            class="d-sm-flex justify-content-sm-center registration-text-sm registration-form-item"
            id="registration-confidential-text"
            href="javascript:void(0);"
        >
            <u>Политика конфиденциальности</u>
        </a>
    </div>
</form>

templates/forms/confirm-form.html
{% load static %}

<form class="justify-content-xl-center custom-card confirm-form" action="{% url 'clients:reg_request_confirm' %}">
    {% csrf_token %}
    <h1 class="confirm-form__title">
        ЗАЯВКА НА РЕГИСТРАЦИЮ ПРИНЯТА
    </h1>
    <p>Ваш заявка принята, наш специалист свяжется<br/> с вами в ближайшее время.</p>
    <div class="text-center registration-form-btn confirm-form__confirm-btn-wrapper">
        <button class="btn btn-primary btn-sign-in confirm-form__confirm-btn" type="submit">Ок</button>
    </div>
    <div class="confirm-form__close-btn-wrapper">
        <svg class="confirm-form__close-btn-icon" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g opacity="0.5" clip-path="url(#clip0_1002_939)">
                <path d="M10.0551 9.00517L17.771 1.28931C18.0688 1.0017 18.077 0.527154 17.7894 0.229355C17.5018 -0.0684449 17.0273 -0.0767024 16.7295 0.210907C16.7232 0.216924 16.7171 0.223074 16.711 0.229355L8.99509 7.94522L1.27921 0.229311C0.981409 -0.0582986 0.506862 -0.050041 0.219252 0.247759C-0.0613305 0.538267 -0.0613305 0.998802 0.219252 1.28931L7.93513 9.00517L0.219252 16.721C-0.0734094 17.0137 -0.0734094 17.4883 0.219252 17.781C0.511957 18.0736 0.986504 18.0736 1.27921 17.781L8.99509 10.0651L16.711 17.781C17.0088 18.0686 17.4833 18.0603 17.7709 17.7625C18.0515 17.472 18.0515 17.0115 17.7709 16.721L10.0551 9.00517Z" fill="#242A35"/>
            </g>
            <defs>
                <clipPath id="clip0_1002_939">
                    <rect width="18" height="18" fill="white"/>
                </clipPath>
            </defs>
        </svg>
        <button class="confirm-form__close-btn" type="submit"></button>
    </div>
</form>

templates/forms/confirm-recovery.html
{% load static %}

<form class="justify-content-xl-center custom-card confirm-form" action="{% url 'clients:request_pass' %}">
    {% csrf_token %}
    <h1 class="confirm-form__title">
        ВОССТАНОВЛЕНИЕ ПАРОЛЯ
    </h1>
    <p>На Ваш адрес электронной почты отправлено письмо со ссылкой на восстановление доступа.</p>
    <div class="text-center registration-form-btn confirm-form__confirm-btn-wrapper">
        <button class="btn btn-primary btn-sign-in confirm-form__confirm-btn" type="submit">Ок</button>
    </div>
    <div class="confirm-form__close-btn-wrapper">
        <svg class="confirm-form__close-btn-icon" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g opacity="0.5" clip-path="url(#clip0_1002_939)">
                <path d="M10.0551 9.00517L17.771 1.28931C18.0688 1.0017 18.077 0.527154 17.7894 0.229355C17.5018 -0.0684449 17.0273 -0.0767024 16.7295 0.210907C16.7232 0.216924 16.7171 0.223074 16.711 0.229355L8.99509 7.94522L1.27921 0.229311C0.981409 -0.0582986 0.506862 -0.050041 0.219252 0.247759C-0.0613305 0.538267 -0.0613305 0.998802 0.219252 1.28931L7.93513 9.00517L0.219252 16.721C-0.0734094 17.0137 -0.0734094 17.4883 0.219252 17.781C0.511957 18.0736 0.986504 18.0736 1.27921 17.781L8.99509 10.0651L16.711 17.781C17.0088 18.0686 17.4833 18.0603 17.7709 17.7625C18.0515 17.472 18.0515 17.0115 17.7709 16.721L10.0551 9.00517Z" fill="#242A35"/>
            </g>
            <defs>
                <clipPath id="clip0_1002_939">
                    <rect width="18" height="18" fill="white"/>
                </clipPath>
            </defs>
        </svg>
        <button class="confirm-form__close-btn" type="submit"></button>
    </div>
</form>

templates/forms/contact.html
{% extends "main.html" %}

{% block page %}
	{% block content %}
        <h4>Контактная информация</h4>
        <hr>
        <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                    {% if id %}
                    <form class="contactForm" method="post" action="{% url 'clients:edit' id %}">
                    {% else %}
                    <form class="contactForm" method="post" action="{% url 'clients:edit' %}">
                    {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row {{ field.name }}-row">
                                {% if not field.is_hidden %}
                                    <label class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                                {% endif %}
                                <div class="col-sm-8">
                                    {{ field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-8 offset-sm-4 errors {{ field.name }}-error"></div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>
              </div>
            </div>
        </div> 

	{% endblock %}
{% endblock %}

templates/forms/csv_upload_form.html
<h2>Загрузить CSV файл</h2>
<form method="POST" enctype="multipart/form-data" action="{{ action_url }}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="button">Загрузить</button>
</form>

templates/forms/file_selection.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Выберите файл для импорта заказов</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form class="modal-form fileSelectionForm" method="post" action="{% url 'orders:import-xlsx' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}

                    {{ field }}
                    <div class="row">
                        <div class="offset-sm-1 errors {{ field.name }}-error"></div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Загрузить</button>
            </form>
        </div>
    </div>
  </div>

templates/forms/share-link.html
{% load static %}
<div class="share-link-dialog hidden" id="share-link-form">
    <div class="modal-content" id="share-link-content">
        <div class="modal-body">
            <input id="share-link" type="text" value="{{ share_link }}" style="width: 500px;">
            <label class="share-link-label" for="share-link">
                <img src="{% static 'img/copy_icon.svg' %}" alt="">
            </label>
        </div>
    </div>
</div>

templates/forms/sign-in.html
{% load static %}


<form class="justify-content-xl-center registration-form custom-card" method="post" action="{% url 'clients:reg_request' %}">
    {% csrf_token %}
    <div class="d-flex flex-column flex-nowrap">
        <div class="d-sm-flex flex-row title-registration-form registration-form-item">
            <p id="title-part-1">РЕГИСТРАЦИЯ</p>
            <p class="cursor-pointer" id="title-part-2">/&nbsp;<a id="entry" data-url="{% url 'clients:login' %}">вход</a></p>
        </div>
        {% for field in form %}
            {% if not field.is_hidden %}
                {% if field.label != "Captcha" %}
                <div class="registration-form-item">
                    <label class="default-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% else %}
                <div class="registration-form-captcha">
                    {{ field }}
                </div>
                {% endif %}
            {% endif %}
        {% endfor %}
        <div class="text-center registration-form-btn">
            <button class="btn btn-primary btn-send-order font-weight-bold" type="submit">Отправить заявку</button>
        </div>
        <a class="d-sm-flex justify-content-sm-center registration-text-sm registration-form-item" id="registration-confidential-text" href="#">
            <u>Политика конфиденциальности</u>
        </a>
    </div>
</form>

templates/forms/size_selection.html
{% load static %}
{% load catalog_tags %}

<div name="form">
    {% csrf_token %}
    <h5 class="sizes-selection__title">Выберите размер и количество</h5>
    <p class="sizes-selection__subtitle">размер, средний вес</p>

    {% include "components/product/sizes.html" with stock_and_cost=stock_and_cost cart=cart %}

    <div class="d-flex sizes-selection__bottom-row">
        <div class="sizes-selection__sum font-weight-bold">0</div>
        <div class="font-weight-bold sizes-selection__currency">руб</div>
        <button name="sizes-selection-add-to-cart-button" class="btn btn-primary font-weight-bold sizes-selection__add-to-cart-button">в корзину</button>
        <div class="sizes-selection__total-group">
            <div class="font-weight-bold sizes-selection__total">
                Всего: <span class="sizes-selection__total-count">0</span> шт
            </div>
            <!-- <div>
                В наличии: <span class="sizes-selection__available-count">0</span> шт
            </div> -->
            <div><span class="sizes-selection__total-weight">0</span> г</div>
        </div>
    </div>

</div>