CabinetOpt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import custom_404_handler, custom_500_handler, custom_403_handler


handler404 = custom_404_handler
handler500 = custom_500_handler
handler403 = custom_403_handler

urlpatterns = [
    path('admin/'       , admin.site.urls),
    path('api-auth/'    , include('rest_framework.urls')),
    path('clients/'     , include('clients.urls')),
    path('users/'       , include('users.urls')),
    path('catalog/'     , include('catalog.urls')),
    path('orders/'      , include('orders.urls')),
    path('cart/'        , include('cart.urls')),
    path('summernote/'  , include('django_summernote.urls')),
    path('condition/'   , include('settings_and_conditions.urls')),
    path('django-rq/'   , include('django_rq.urls')),
    path('shared_links/', include('shared_links.urls')),
    path('', render, kwargs={'template_name': 'index.html'}, name='start_page'),
    path('forbidden/'   , views.forbidden_view, name='forbidden_view'),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/' , include('debug_toolbar.urls')),
        path('silk/', include('silk.urls', namespace='silk')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, register_converter
from django.urls.converters import SlugConverter


from . import views
    
class SizeConverter:
    regex = '[.-a-zA-Z0-9_]*'

    def to_python(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value

    def to_url(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value    

register_converter(SizeConverter, 'size')

app_name = "cart"
urlpatterns = [
    path(''                                     , views.cart_detail, name='cart_detail'),
    path('send/<str:product_id>/'               , views.send_to_cart),
    path('add/<str:product_id>/'                , views.cart_add, name='cart_add'),
    path('add/sizes/<str:product_id>/'          , views.cart_add_sizes, name='cart_add_sizes'),
    path('info/'                                , views.cart_info),
    path('info/<str:product_id>/'               , views.cart_info),
    path('info/<str:product_id>/<size:size>'    , views.cart_info),
    path('remove/<str:product_id>/'             , views.cart_remove, name='cart_remove'),
    path('remove/<str:product_id>/<size:size>'  , views.cart_remove_size, name='cart_remove_size'),
    path('order/create/'                        , views.add_order, name='create'),
    path('errors/'                              , views.cart_detail_with_errors, name='errors'),
    path('product/<str:prod_id>/'               , views.edit_product, name='product_editing'),
]

catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path('filters/'                       , views.FiltersView.as_view()),
    path('products/'                      , views.ProductView.as_view(), name='products'),
    path('products/<str:key>/'            , views.ProductView.as_view()),
    # path('сertificates/'                  , views.CertificateView.as_view(), name='сertificates'),
    # path('services/'                      , views.ServiceView.as_view(), name='services'),
    path('product/<slug:prod_id>/'        , views.ProductCardView.as_view(), name='product'),
    path('upload/products'                , views.upload_products),
    path('remove/images/<slug:prod_id>'   , views.remove_images),
    path('upload/images'                  , views.upload_images),
    path('upload/videos'                  , views.upload_videos),
    path('upload/price'                   , views.upload_price),
    path('upload/stock_and_costs'         , views.upload_stock_and_costs),
    path('pickup_products/'               , views.pickup_products),
    path('stocks_and_costs/'              , views.stocks_and_costs),
    path('product/accessories'            , views.product_accessories),
    path('product/analogues'              , views.product_analogues),
    path('product/alike-products'         , views.alike_products),
    path('product/sizes/<slug:prod_id>/'  , views.sizes_selection, name='sizes_selection'),
    path('products/pages/count/'          , views.catalog_pages_count),
    path('search-error/'                  , views.search_error),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path('reg_request/'            , views.register, name='reg_request'),
    path('reg_request_confirm/'    , views.register_confirm, name='reg_request_confirm'),
    path('login/'                  , views.login, name='login'),
    path('logout/'                 , views.logout, name='logout'),
    path('check_login/'            , views.check_login, name='check_login'),
    path('login_recovery/'         , views.login_recovery, name='login_recovery'),
    path('change_pass/<str:id>/'   , views.change_password, name='change_pass'),
    path('request_pass/'           , views.request_password, name='request_pass'),
    path('recovery_pass/<str:id>/' , views.recovery_password, name='recovery_pass'),
    path('contact/'                , views.ContactDetailView.as_view(), name='contact'),
    path('contact/edit/<str:id>/'  , views.ContactDetailEditView.as_view(), name='edit'),
    path('contact/edit/'           , views.ContactDetailCreateView.as_view(), name='edit'),
    path('manager/'                , views.ManagerView.as_view(), name='manager'),
    path('manager/add/'            , views.ManagerAddView.as_view(), name='add_manager'),
    path('generate-password/'      , views.generate_password, name='generate_password'),
]

orders/urls.py
from django.urls import path, register_converter
from datetime import datetime

from . import views

class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value    

register_converter(DateConverter, 'data')

app_name = "orders"
urlpatterns = [
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('order/edit/<slug:order_id>/', views.EditOrderView.as_view(), name='edit'),
    path('order/update/<slug:order_id>/', views.UpdateOrderView.as_view(), name='update'),
    path('order/split/<slug:order_id>/', views.SplitOrderView.as_view(), name='split'),
    path('order/remove/<slug:order_id>/', views.remove_order, name='remove'),
    path('order/create/<slug:order_id>/', views.CreateOrderView.as_view(), name='create'),
    path('order/item/create', views.add_order_item),
    path('stocks_and_costs/', views.stocks_and_costs),
    path('order/export', views.unload_orders),
    path('order/export/<data:data_from>', views.unload_orders),
    path('order/export/<data:data_from>/<data:data_to>', views.unload_orders),
    path('order/export/pdf/<slug:order_id>/', views.ExportPDFView.as_view(), name='export-pdf'),
    path('order/export/xlsx/<slug:order_id>/', views.ExportXLSXView.as_view(), name='export-xlsx'),
    path('order/import/xlsx/', views.import_xlsx, name='import-xlsx'),
    path('order/update/number', views.update_order_number),
    path('order/product/<str:order_id>/<str:prod_id>/', views.edit_product, name='product_editing'),
]

settings_and_conditions/urls.py
from django.urls import path

from . import views

app_name = "settings_and_conditions"

urlpatterns = [
    path('promo/', views.promo, name='promo'),
    path('guarantee/', views.guarantee, name='guarantee'),
    path('policy/', views.policy, name='policy'),
    path('delivery/', views.delivery, name='delivery'),
    path('about/', views.about, name='about'),
    path('where-to-buy/', views.where_to_buy, name='where-to-buy'),
]

templates/components/main/footer.html
{% load static %}
<nav class="navbar navbar-dark" style="background: #242A35;">
    <div class="container footer-container">
        <div class="row">
            <img class="navbar-custom__logo" src="{% static 'img/logo-white.svg' %}" alt="Лого">
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col-5">
                <p>КОНТАКТЫ</p>
                <p style="max-height: 30px;"></p>
                <p style="margin-bottom: 30px; max-width: 400px;">{{ organization.address }}</p>
                <p style="margin-bottom: 1px;">{{ organization.phone }}</p>
                <p style="margin-bottom: 30px;">{{ organization.email }}</p>
                {% if organization.additional_phone %}
                <p style="margin-bottom: 1px;">{{ organization.additional_phone }}</p>
                {% endif %}
                {%  if organization.additional_email %}
                <p>{{ organization.additional_email }}</p>
                {% endif %}
            </div>
            <div class="col-3">
                {% if not request.session.login %}
                    <p>КАТАЛОГ</p>
                    <p>КОРЗИНА</p>
                    <p>ЗАКАЗЫ</p>
                    <p>ЛИЧНЫЙ КАБИНЕТ</p>
                    <!-- <p>
                        <a class="text-nowrap text-white"
                        name="login"
                        data-url="{% url 'start_page' %}"
                        href="javascript:void(0);">
                            ВХОД
                        </a>
                    </p> -->
                {% else %}
                    <p><a href="{% url 'catalog:products' %}">КАТАЛОГ</a></p>
                    <p><a href="{% url 'cart:cart_detail' %}">КОРЗИНА</a></p>
                    <p><a href="{% url 'orders:orders' %}">ЗАКАЗЫ</a></p>
                    <p><a href="{% url 'clients:contact' %}">ЛИЧНЫЙ КАБИНЕТ</a></p>
                    <p>
                        <a 
                            name="logout"
                            data-url="{% url 'clients:logout' %}"
                            href="javascript:void(0);">
                            ВЫХОД
                        </a>
                    </p>
                {% endif %}
            </div>
            <div class="col-3">
                <p><a href="{% url 'settings_and_conditions:promo' %}">Акции</a></p>
                <p><a href="{% url 'settings_and_conditions:guarantee' %}">Гарантия и возврат</a></p>
                <p><a href="{% url 'settings_and_conditions:policy' %}">Политика обработки персональных данных</a></p>
                <p><a href="{% url 'settings_and_conditions:delivery' %}">Доставка</a></p>
                <p><a href="{% url 'settings_and_conditions:about' %}">О заводах TALANT</a></p> 
            </div>
        </div>
        <div class="row-social">
            <a href="https://vk.com/talant_jewelry
            " target="_blank">
                <img class="" src="{% static 'img/vk.png' %}" alt="ВКонтакте">
            </a>
            <a href="https://t.me/talant_jewelry
            " target="_blank">
                <img class="" src="{% static 'img/telegram.png' %}" alt="Телеграмм">
            </a>
            <a href="tel:+78004445785">
                <img class="" src="{% static 'img/phone.png' %}" alt="Телефон">
            </a>
        </div>
    </div>
</nav>