CabinetOpt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import custom_404_handler, custom_500_handler, custom_403_handler


handler404 = custom_404_handler
handler500 = custom_500_handler
handler403 = custom_403_handler

urlpatterns = [
    path('admin/'       , admin.site.urls),
    path('api-auth/'    , include('rest_framework.urls')),
    path('clients/'     , include('clients.urls')),
    path('users/'       , include('users.urls')),
    path('catalog/'     , include('catalog.urls')),
    path('orders/'      , include('orders.urls')),
    path('cart/'        , include('cart.urls')),
    path('summernote/'  , include('django_summernote.urls')),
    path('condition/'   , include('settings_and_conditions.urls')),
    path('django-rq/'   , include('django_rq.urls')),
    path('shared_links/', include('shared_links.urls')),
    path('', render, kwargs={'template_name': 'index.html'}, name='start_page'),
    path('forbidden/'   , views.forbidden_view, name='forbidden_view'),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/' , include('debug_toolbar.urls')),
        path('silk/', include('silk.urls', namespace='silk')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, register_converter
from django.urls.converters import SlugConverter


from . import views
    
class SizeConverter:
    regex = '[.-a-zA-Z0-9_]*'

    def to_python(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value

    def to_url(self, value):
        if not value:
            return ''
        if value == 'None':
            return ''
        return value    

register_converter(SizeConverter, 'size')

app_name = "cart"
urlpatterns = [
    path(''                                     , views.cart_detail, name='cart_detail'),
    path('send/<str:product_id>/'               , views.send_to_cart),
    path('add/<str:product_id>/'                , views.cart_add, name='cart_add'),
    path('add/sizes/<str:product_id>/'          , views.cart_add_sizes, name='cart_add_sizes'),
    path('info/'                                , views.cart_info),
    path('info/<str:product_id>/'               , views.cart_info),
    path('info/<str:product_id>/<size:size>'    , views.cart_info),
    path('remove/<str:product_id>/'             , views.cart_remove, name='cart_remove'),
    path('remove/<str:product_id>/<size:size>'  , views.cart_remove_size, name='cart_remove_size'),
    path('order/create/'                        , views.add_order, name='create'),
    path('errors/'                              , views.cart_detail_with_errors, name='errors'),
    path('product/<str:prod_id>/'               , views.edit_product, name='product_editing'),
]

catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path('filters/'                       , views.FiltersView.as_view()),
    path('products/'                      , views.ProductView.as_view(), name='products'),
    path('products/<str:key>/'            , views.ProductView.as_view()),
    # path('сertificates/'                  , views.CertificateView.as_view(), name='сertificates'),
    # path('services/'                      , views.ServiceView.as_view(), name='services'),
    path('product/<slug:prod_id>/'        , views.ProductCardView.as_view(), name='product'),
    path('upload/products'                , views.upload_products),
    path('remove/images/<slug:prod_id>'   , views.remove_images),
    path('upload/images'                  , views.upload_images),
    path('upload/videos'                  , views.upload_videos),
    path('upload/price'                   , views.upload_price),
    path('upload/stock_and_costs'         , views.upload_stock_and_costs),
    path('pickup_products/'               , views.pickup_products),
    path('stocks_and_costs/'              , views.stocks_and_costs),
    path('product/accessories'            , views.product_accessories),
    path('product/analogues'              , views.product_analogues),
    path('product/alike-products'         , views.alike_products),
    path('product/sizes/<slug:prod_id>/'  , views.sizes_selection, name='sizes_selection'),
    path('products/pages/count/'          , views.catalog_pages_count),
    path('search-error/'                  , views.search_error),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path('reg_request/'            , views.register, name='reg_request'),
    path('reg_request_confirm/'    , views.register_confirm, name='reg_request_confirm'),
    path('login/'                  , views.login, name='login'),
    path('logout/'                 , views.logout, name='logout'),
    path('check_login/'            , views.check_login, name='check_login'),
    path('login_recovery/'         , views.login_recovery, name='login_recovery'),
    path('change_pass/<str:id>/'   , views.change_password, name='change_pass'),
    path('request_pass/'           , views.request_password, name='request_pass'),
    path('recovery_pass/<str:id>/' , views.recovery_password, name='recovery_pass'),
    path('contact/'                , views.ContactDetailView.as_view(), name='contact'),
    path('contact/edit/<str:id>/'  , views.ContactDetailEditView.as_view(), name='edit'),
    path('contact/edit/'           , views.ContactDetailCreateView.as_view(), name='edit'),
    path('manager/'                , views.ManagerView.as_view(), name='manager'),
    path('manager/add/'            , views.ManagerAddView.as_view(), name='add_manager'),
    path('generate-password/'      , views.generate_password, name='generate_password'),
]

orders/urls.py
from django.urls import path, register_converter
from datetime import datetime

from . import views

class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value    

register_converter(DateConverter, 'data')

app_name = "orders"
urlpatterns = [
    path('orders/', views.OrderView.as_view(), name='orders'),
    path('order/edit/<slug:order_id>/', views.EditOrderView.as_view(), name='edit'),
    path('order/update/<slug:order_id>/', views.UpdateOrderView.as_view(), name='update'),
    path('order/split/<slug:order_id>/', views.SplitOrderView.as_view(), name='split'),
    path('order/remove/<slug:order_id>/', views.remove_order, name='remove'),
    path('order/create/<slug:order_id>/', views.CreateOrderView.as_view(), name='create'),
    path('order/item/create', views.add_order_item),
    path('stocks_and_costs/', views.stocks_and_costs),
    path('order/export', views.unload_orders),
    path('order/export/<data:data_from>', views.unload_orders),
    path('order/export/<data:data_from>/<data:data_to>', views.unload_orders),
    path('order/export/pdf/<slug:order_id>/', views.ExportPDFView.as_view(), name='export-pdf'),
    path('order/export/xlsx/<slug:order_id>/', views.ExportXLSXView.as_view(), name='export-xlsx'),
    path('order/import/xlsx/', views.import_xlsx, name='import-xlsx'),
    path('order/update/number', views.update_order_number),
    path('order/product/<str:order_id>/<str:prod_id>/', views.edit_product, name='product_editing'),
]

settings_and_conditions/urls.py
from django.urls import path

from . import views

app_name = "settings_and_conditions"

urlpatterns = [
    path('promo/', views.promo, name='promo'),
    path('guarantee/', views.guarantee, name='guarantee'),
    path('policy/', views.policy, name='policy'),
    path('delivery/', views.delivery, name='delivery'),
    path('about/', views.about, name='about'),
    path('where-to-buy/', views.where_to_buy, name='where-to-buy'),
]

templates/index.html
{% extends "main.html" %}

{% block page %}
	{% block content %}

	{% endblock %}
{% endblock %}

templates/main.html
{% load static %}
{% load humanize %}
{% load client_tags %}

<!DOCTYPE html>
<html lang="ru" style="visibility:hidden">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Личный кабинет ЮЛ</title>

    <link rel="stylesheet" href="{% static '/font-awesome/css/font-awesome.min.css' %}">
    <link rel="icon" href="{%  static 'favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/img/favicons/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'android-chrome-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="512x512" href="{% static 'android-chrome-512x512.png' %}">
    <link rel="apple-touch-icon" href="{% static '/img/favicons/apple-touch-icon.png' %}">
    <link rel="manifest" href="{%  static 'site.webmanifest' %}">

    <style>
        .main-background {
            background: url('{% static "img/login-background.png" %}'), lightgray 50% / cover no-repeat;
        }
    </style>

    <!-- yandex geo -->
    <script type="text/javascript" src="https://api-maps.yandex.ru/v3/?lang=ru_RU&apikey=71db1fad-7278-47f2-9695-9d4486453e8c"></script>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();
        for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
        k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
    
        ym(98943384, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/98943384" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

</head>
<body>
    <script src="{% static 'main.js' %}"></script>
    {% if not request.session.login %}
        <nav class="navbar navbar-custom" id="login-menu">
            <img class="navbar-custom__logo" src="{% static 'img/logo-white.svg' %}" alt="Лого">
            <!-- <a
                class="text-nowrap text-white"
                id="registration-form-switch"
                data-url="{% url 'clients:reg_request' %}"
                href="#"
            >
                Оптовая торговля
            </a> -->
            <span id="add-to-favorites" class="text-nowrap text-white">&nbsp;Добавить в избранное&nbsp;</span>
            <!-- <a class="text-nowrap text-white underlined" href="https://talantgold.ru/" target="_blank">Розничная торговля</a> -->
        </nav>

        <div id="main" class="main-background">
            {% block form %}
            {% endblock %}
        </div>
    {% else %}
        <nav class="d-lg-flex justify-content-lg-start navbar navbar-dark navbar-expand-md navbar-fixed navbar-custom-main" id="main-menu">
            <button class="navbar-toggler navbar-custom-pos" data-toggle="collapse" data-target="#menu-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="menu-collapse" class="collapse navbar-collapse menu-collapsed">
                <ul class="navbar-nav navbar-custom-main__navbar-nav">
                    <li class="d-lg-flex align-items-lg-center nav-item">
                        <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-products" href="{% url 'catalog:products' %}">
                            Каталог
                        </a>
                    </li>
                    <!-- <li class="d-lg-flex align-items-lg-center nav-item">
                        <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-orders" href="{% url 'orders:orders' %}">
                            Заказы
                        </a>
                    </li> -->
                    <li class="d-lg-flex align-items-lg-center nav-item">
                        <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-orders" href="{% url 'settings_and_conditions:promo' %}">
                            Акции
                        </a>
                    </li>
                    <li class="d-lg-flex align-items-lg-center nav-item">
                        <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-orders" href="{% url 'settings_and_conditions:delivery' %}">
                            Доставка
                        </a>
                    </li>
                    <li class="d-lg-flex align-items-lg-center nav-item">
                        <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-orders" href="{% url 'settings_and_conditions:about' %}">
                            О заводах TALANT
                        </a>
                    </li>
                </ul>
            </div>
            <div class="d-flex align-items-center row" id="main-menu-info">
                <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-orders" href="{% url 'settings_and_conditions:where-to-buy' %}">
                    Где купить
                </a>
                <a class="text-nowrap text-center text-white d-lg-flex justify-content-lg-center align-items-lg-center main-menu-item" id="link-orders" href="{% url 'orders:orders' %}">
                    Заказы
                </a>
                <a class="text-nowrap text-center text-white d-flex justify-content-center align-items-center main-menu-item" id="link-client" href="{% url 'clients:contact' %}">
                    <img class="d-flex align-items-center main-menu-item" id="pa-user" src="{% static 'img/pa-user-icon.svg' %}">
                    <!-- <p id="login-info">{{ request.session|login_info }}</p> -->
                </a>
                <a class="text-nowrap text-center text-white d-flex justify-content-center align-items-center main-menu-item" name="share-link-dialog" id="link-client" href="javascript:void(0);" style="position: relative;">
                    <img class="d-flex align-items-center main-menu-item" src="{% static 'img/share-icon.svg' %}">
                    <div class="alert share-link-alert d-flex rounded" role="alert">
                        <img src="{% static 'img/checkmark_8224776.svg' %}" alt="">
                        <div class="alert-message share-link-message d-flex align-items-center">
                            Ссылка скопированна.
                        </div>
                    </div>
                    <!-- <p id="login-info">{{ request.session|login_info }}</p> -->
                </a>
                <!-- <img class="d-flex align-items-center main-menu-item" id="main-menu-hart" src="{% static 'img/hart.svg' %}"> -->
                <a class="d-flex align-items-center main-menu-item" id="link-cart" href="{% url 'cart:cart_detail' %}">
                    <img class="d-flex" id="main-menu-cart" src="{% static 'img/cart.svg' %}">
                </a>
                <div id="cart-container">
                    {% with total_items=cart|length %}
                    <div class="d-flex flex-nowrap justify-content-center align-items-end row" id="cart-info">
                        <span class="d-sm-flex cart-total-sum">{{ cart.get_total_price|floatformat:"0"|intcomma }}</span>
                        <span class="d-sm-flex cart-currency">₽</span>
                        <span class="flex-nowrap cart-total-weight">/ {{ cart.get_total_weight|floatformat:2 }} г</span>
                    </div>
                    {% endwith %}
                </div>
                <a class="text-nowrap text-center text-white d-flex justify-content-center align-items-center navbar-custom-main__logout-link" name="logout" data-url="{% url 'clients:logout' %}" href="javascript:void(0);">
                    <i>выход</i>
                    <!-- <svg class="navbar-custom-main__logout-icon" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M7.01297 6.39978L12.3419 1.0709C12.5475 0.872263 12.5532 0.544522 12.3546 0.33885C12.156 0.133178 11.8282 0.127475 11.6226 0.32611C11.6182 0.330265 11.614 0.334512 11.6098 0.33885L6.28089 5.66773L0.952 0.33882C0.746328 0.140186 0.418587 0.145889 0.219952 0.351561C0.0261707 0.552197 0.0261707 0.870261 0.219952 1.0709L5.54884 6.39978L0.219952 11.7287C0.0178286 11.9308 0.0178286 12.2586 0.219952 12.4607C0.422105 12.6628 0.749847 12.6628 0.952 12.4607L6.28089 7.13182L11.6098 12.4607C11.8155 12.6593 12.1432 12.6536 12.3418 12.448C12.5356 12.2473 12.5356 11.9293 12.3418 11.7287L7.01297 6.39978Z" fill="white"/>
                    </svg> -->
                </a>
            </div>
            <img class="navbar-custom-main__logo" src="{% static 'img/logo-white.svg' %}" alt="Лого">
        </nav>

        <div class="container-fluid main-content">
            {% block page %}
                {% block content %}
                {% endblock %}
            {% endblock %}
        </div>

    {% endif %}

    {% include "components/main/footer.html" with organization=organization%}
    {% include "forms/share-link.html" with share_link=share_link %}

    <div class="sign-in-form-layout" id="registration-form"></div>
    <div class="background-overlay hidden"></div>
</body>
</html>

templates/reg_order.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Регистрация нового клиента</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form class="registration-form" method="post" action="{% url 'clients:create_request' %}">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group row {{ field.name }}-row">
                        <label class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                        </div>
                        <!-- {% if field.errors%}
                            <div class="error">{{field.errors}}</div>
                        {% endif %} -->
                    </div>
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-4 errors {{ field.name }}-error"></div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
  </div>